apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret
data:
    .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJlYzItNTItNjYtMjQyLTIuYXAtc291dGgtMS5jb21wdXRlLmFtYXpvbmF3cy5jb206ODA4MiI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWVdSdGFXNDZVbUZuYUhWQU1UazVNZz09IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
