apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJlYzItMTMtMjMzLTE4NC02My5hcC1zb3V0aC0xLmNvbXB1dGUuYW1hem9uYXdzLmNvbTo4MDg1IjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlVtRm5hSFZBTVRrNU1nPT0iCgkJfSwKCQkiZWMyLTEzLTIzMy0yMzItMTc5LmFwLXNvdXRoLTEuY29tcHV0ZS5hbWF6b25hd3MuY29tOjgwODUiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2VW1GbmFIVkFNVGs1TWc9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
