apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJlYzItMTMtMjMzLTEzOS0xNzIuYXAtc291dGgtMS5jb21wdXRlLmFtYXpvbmF3cy5jb206ODA4NSI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZVbUZuYUhWQU1UazVNZz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
